# First print your name in the cell below then save this file. (or something nice about your instructor)

In [ ]:
# NOTE TO GRADER: ZACH IS ALLOWING ME TO SUBMIT ON WEDNESDAY AT NOON INSTEAD. MY DAYS OFF FROM WORK ARE TUES AND WED SO I NEED THAT ACCOMODATION. THANK YOU!

In [ ]:
# In this cell print your name 

print("Brandon Ljikovic")

Brandon Ljikovic

In [2]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [3]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [4]:
# Load data here
df = pd.read_csv("../data/listings.csv")

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [4]:
# 1. How many listings are there with a price less than 100?

#df = pd.read_csv("../data/listings.csv")

#filter of true and false values for the price column
underHundred = df['price'] < 100 

#Only true values in new df
listingsUnderHundred = df[underHundred]

# .shape[0] will give you the number of rows in a dataframe
countUnderHundred = listingsUnderHundred.shape[0]
print(countUnderHundred)
df.columns

22778

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='str')

In [5]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

#df = pd.read_csv("../data/listings.csv")


df_bk = df[df['neighbourhood_group'] == 'Brooklyn']

#Me trying to make sense of this: 
#the dataframe specifically the neighborhood group that is equal to 'Brooklyn'
# and make a dataframe with just those rows

count_bk = df_bk.shape[0]
print(count_bk)

18632

In [13]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
bkPrices = df_bk['price']
listingsUnderHundred = df_bk[bkPrices < 100 ].shape[0]
print(listingsUnderHundred)

10473

In [7]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
df.head()
#df['host_name']
names = ['Michael', 'David', 'John', 'Daniel']
nameFilter= df['host_name'].isin(names)
filteredNames = df[nameFilter]
total = nameFilter.sum()
print(total)

1258

In [8]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 

df['adjusted_price'] = df['price']
df['adjusted_price'] = np.where(df['neighbourhood'] == 'Williamsburg', df['price'] + 100 , df['price'])

df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,175
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,75
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,60
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,175
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340,65

In [6]:
# 6. What % of the rooms 
# are private, and what % of the rooms are shared.  

#in my search including looking at the .csv , I found that 
# 'Private room' is what I am looking for in 'room_type'
# also 'Shared room'

#df.columns
# NOTE: could have used the lines below in the lecture but this wouldn't isolate
# the two types of rooms.
# dfp = df.neighbourhood_group.value_counts(normalize=True) 
# dfp

type = df['room_type']
private = (type == 'Private room').sum()
shared = (type == 'Shared room').sum()

total = len(df)

privatePercent = private / total * 100
sharedPercent = shared / total * 100 

print( f"Private rooms make up {privatePercent} %  and shared rooms make up {sharedPercent} % " )

#print(shared

Private rooms make up 45.444580566122895 %  and shared rooms make up 2.12134889419047 %

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [5]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.

df.groupby('neighbourhood_group').size()

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
dtype: int64

In [6]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 

df.groupby('neighbourhood_group')['price'].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [7]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
df.groupby('room_type')['price'].mean()

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [8]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 

nhGroups = df.groupby('neighbourhood_group')
nhGroups['price'].agg(['min' , 'max'])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [9]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.

nhGroups ['price'].agg(['mean'])

                           mean
neighbourhood_group
Bronx                 92.751479
Brooklyn             120.225258
Manhattan            191.880466
Queens                99.754965
Staten Island        110.947214

In [10]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

nhGroups = df.groupby('neighbourhood_group')
nhGroups['price'].agg(['count','min' , 'max', 'mean', 'median', 'std'])

                     count  min    max        mean  median         std
neighbourhood_group
Bronx                 1183   16   1404   92.751479    69.0   95.787081
Brooklyn             18632    0  10000  120.225258    90.0  180.136376
Manhattan            20580    0  10000  191.880466   129.0  428.682578
Queens                5791    0  10000   99.754965    70.0  207.648739
Staten Island          341   19   1200  110.947214    79.0  122.676152

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [12]:
# 1. Load the `prices.csv` and the `n_listings.csv`
priceDf = pd.read_csv("../data/prices.csv")
listingDf = pd.read_csv("../data/n_listings.csv", sep = ";")

In [14]:
# 2. Do join that keeps all the records for each table.
joinedDf = pd.merge(priceDf, listingDf, on = "neighbourhood_group", how = "outer")

joinedDf

  neighbourhood_group   mean_price  n_listings
0               Bronx    92.751479      1183.0
1            Brooklyn   120.225258     18632.0
2          LongIsland          NaN      4121.0
3           Manhattan   191.880466     20580.0
4              Queens    99.754965         NaN
5       Staten Island   110.947214         NaN

In [15]:
# 3. Save your joined csv as `joined.csv` into the data folder. 

joinedDf.to_csv("../data/joined.csv", index=False)

In [16]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`

joinedDf2 = pd.read_csv("../data/joined.csv")

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.